apiVersion: v1
kind: Pod
metadata:
  name: webappdemo
  labels:
    name: webappdemo
    app: demo
spec:
  containers:
  - name: webappdemo
    image: $ACR_DNS/WebApp:$BUILD_ID
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webappdemo-k8sservice
  labels:
    name: webappdemo
    app: demo
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: webappdemo
    app: demo
  type: LoadBalancer